name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.25.4
  rxdart: ^0.26.0-nullsafety.1
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  enhanced_meteorify:
    path: ../
  
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
