name: meteorify
description: >-
  A dart package to interact with Meteor.
  Meteorify provides the following features:
  - Connect to Meteor servers
  - Use Meteor Subscriptions
  - Meteor Authentications services
  - Call Custom Methods on meteor servers
  - Access underlying databases
version: 1.0.0
homepage: https://github.com/ShivamArora/meteorify
repository: https://github.com/ShivamArora/meteorify
author: Shivam Arora <email.shivamarora@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ddp: ^0.0.9
  mongo_dart: ^0.3.5

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
