name: enhanced_meteorify
description: |
  Carefully extended meteorify package to interact with the Meteor framework.
  Connect your web or flutter apps, written in Dart, with the Meteor framework.
version: 3.0.2
homepage: https://github.com/wendellrocha/enhanced-meteorify
repository: https://github.com/wendellrocha/enhanced-meteorify

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0
  tuple: ^2.0.0
  shared_preferences: ^2.0.6
  crypto: ^3.0.1
