name: enhanced_meteorify
description: |
  Carefully extended meteorify package to interact with the Meteor framework.
  Connect your web or flutter apps, written in Dart, with the Meteor framework.
version: 3.2.0006
homepage: https://github.com/wendellrocha/enhanced-meteorify
repository: https://github.com/wendellrocha/enhanced-meteorify

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  web_socket_channel: 2.4.3
  tuple: 2.0.2
  shared_preferences: 2.1.0
  crypto: 3.0.3
  meta: 1.11.0
  logger: 2.0.2+1

