name: meteorify
description: A dart package to interact with Meteor
version: 1.0.0
# homepage: https://www.example.com
author: shivamarora <email.shivamarora@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ddp: ^0.0.9
  mongo_dart: ^0.3.5

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
